development:
  secret_token: bbf75b8045e4dd1800df4fff3e396c1ce31df54a3258a9187f989dff99c976455255ff94b412c63fc4fc11692b7658edfd4f155dec895b50b928437e0c32f6e0
  secret_key_base: bbf75b8045e4dd1800df4fff3e396c1ce31df54a3258a9187f989dff99c976455255ff94b412c63fc4fc11692b7658edfd4f155dec895b50b928437e0c32f6e0
  fyber_api_key: b07a12df7d52e6c118e5d47d3f9e60135b109a1f
  fyber_appid: "157"
  fyber_locale: "de"
  fyber_os_version: "6.1"
  fyber_apple_idfa: "2E7CE4B3-F68A-44D9-A923-F4E48D92B31E"
  fyber_apple_idfa_tracking_enabled: "false"
  fyber_ip: "109.235.143.113"
  fyber_offer_types: "112"
  fyber_device: "phone"
  fyber_device_id: "2b6f0cc904d137be2e1730235f5664094b83"
  fyber_provider_uri: "http://api.sponsorpay.com/feed/v1/offers.json"

test:
  secret_token: bbf75b8045e4dd1800df4fff3e396c1ce31df54a3258a9187f989dff99c976455255ff94b412c63fc4fc11692b7658edfd4f155dec895b50b928437e0c32f6e0
  secret_key_base: bbf75b8045e4dd1800df4fff3e396c1ce31df54a3258a9187f989dff99c976455255ff94b412c63fc4fc11692b7658edfd4f155dec895b50b928437e0c32f6e0
  fyber_api_key: b07a12df7d52e6c118e5d47d3f9e60135b109a1f
  fyber_appid: "157"
  fyber_locale: "de"
  fyber_os_version: "6.1"
  fyber_apple_idfa: "2E7CE4B3-F68A-44D9-A923-F4E48D92B31E"
  fyber_apple_idfa_tracking_enabled: "false"
  fyber_ip: "109.235.143.113"
  fyber_offer_types: "112"
  fyber_device: "phone"
  fyber_device_id: "2b6f0cc904d137be2e1730235f5664094b83"
  fyber_provider_uri: "http://api.sponsorpay.com/feed/v1/offers.json"

production:
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fyber_api_key: <%= ENV["FYBER_API_KEY"] %>
  fyber_appid: <%= ENV["FYBER_APPID"] %>
  fyber_locale: <%= ENV["FYBER_LOCALE"] %>
  fyber_os_version: <%= ENV["FYBER_OS_VERSION"] %>
  fyber_apple_idfa: <%= ENV["FYBER_IDFA"] %>
  fyber_apple_idfa_tracking_enabled: <%= ENV["FYBER_IDFA_ENABLED"] %>
  fyber_ip: <%= ENV["FYBER_IP"] %>
  fyber_offer_types: <%= ENV["FYBER_OFFER_TYPES"] %>
  fyber_device: <%= ENV["FYBER_DEVICE"] %>
  fyber_device_id: <%= ENV["FYBER_DEVICE_ID"] %>
  fyber_provider_uri: <%= ENV["FYBER_URI"] %>
